site_name: appJar
site_url: http://appjar.info
site_favicon: /img/favicon.ico
site_dir: ../../../jarvisteach.github.io/
repo_url: https://github.com/jarvisteach/appJar
google_analytics: ['UA-79206647-1', 'appjar.info']
theme: united
theme_dir: custom_united
copyright: <p>&#169; Richard Jarvis, 2015-2017</p>
site_description: The easiest way to build tkinter GUIs in Python.
site_author: Richard Jarvis
extra_css: [extra.css]
strict: true
pages:
- Welcome: index.md
- Fillings:
    - Widgets: pythonWidgets.md
    - Images: pythonImages.md
    - Sounds: pythonSound.md
    - Bars: pythonBars.md
    - Pop-ups: pythonDialogs.md
    - Multiple Windows: pythonSubWindows.md
    - Splashscreen: splash.md
    - Special Characters: specialCharacters.md
    - Beta Widgets...: pythonDevWidgets.md
- Configuration:
    - GUI Options: pythonGuiOptions.md
    - Widgets:
        - Layout: pythonWidgetLayout.md
        - Configuration: pythonWidgetOptions.md
        - Grouping: pythonWidgetGrouping.md
        - The power of WITH: pythonContextManager.md
    - Events:
        - Events: pythonEvents.md
        - Loops & Sleeps: pythonLoopsAndSleeps.md
        - Threads: pythonThreads.md
        - Drag'n Drop: pythonDnD.md
    - Internationalisation: pythonInternationalisation.md
    - Logging: pythonLogging.md
    - Command Line Arguments: pythonCommandLine.md
    - ttk: pythonTtk.md
- Examples:
    - Raspberry Pi Minecraft: examples/minecraft.md
    - Simple Layout: examples/simple.md
- Help:
    - Guidance: guidance.md
    - Installation: Install.md
    - Packaging: packaging.md
    - License: License.md
    - Support: Support.md
    - Acknowledgements: Thanks.md
    - Contributing: contributing.md
    - Change-Log: whatsNew.md
    - Old Documentation: oldDocs.md
    - Other Help:
        - Python: pythonBasics.md
        - Algorithms: algorithms.md
        - Git & PyPi: gitGuide.md
extra:
    theme_inverse: false
